"""
エラーコード定数定義
設計書に準拠したエラーコード体系
"""

# VALIDATION エラー（400）
VALIDATION_INVALID_SQL = "VALIDATION_INVALID_SQL"
VALIDATION_EMPTY_SQL = "VALIDATION_EMPTY_SQL"
VALIDATION_SQL_TOO_LONG = "VALIDATION_SQL_TOO_LONG"
VALIDATION_INVALID_PROMPT = "VALIDATION_INVALID_PROMPT"

# NOT_FOUND エラー（404）
NOT_FOUND_PROBLEM = "NOT_FOUND_PROBLEM"
NOT_FOUND_TABLES = "NOT_FOUND_TABLES"

# DATABASE エラー（500）
DB_CONNECTION_ERROR = "DB_CONNECTION_ERROR"
DB_EXECUTION_ERROR = "DB_EXECUTION_ERROR"
DB_TIMEOUT_ERROR = "DB_TIMEOUT_ERROR"
DB_SYNTAX_ERROR = "DB_SYNTAX_ERROR"
DB_SCHEMA_ERROR = "DB_SCHEMA_ERROR"
DB_NOT_INITIALIZED_ERROR = "DB_NOT_INITIALIZED_ERROR"
DB_DROP_TABLE_ERROR = "DB_DROP_TABLE_ERROR"

# LLM エラー（500/503）
LLM_CONNECTION = "LLM_CONNECTION"
LLM_TIMEOUT = "LLM_TIMEOUT"
LLM_INVALID_RESPONSE = "LLM_INVALID_RESPONSE"
LLM_GENERATION_FAILED = "LLM_GENERATION_FAILED"

# INTERNAL エラー（500）
INTERNAL_ERROR = "INTERNAL_ERROR"

# API特有エラー（400/404/500）
TABLE_CREATION_ERROR = "TABLE_CREATION_ERROR"
PROBLEM_GENERATION_ERROR = "PROBLEM_GENERATION_ERROR"
NO_TABLES = "NO_TABLES"
PROBLEM_NOT_FOUND = "PROBLEM_NOT_FOUND"
SCHEMA_FETCH_ERROR = "SCHEMA_FETCH_ERROR"