"""
エラーコード定数定義
設計書に準拠したエラーコード体系
"""

# VALIDATION エラー（400）
VALIDATION_INVALID_SQL = "VALIDATION_INVALID_SQL"
VALIDATION_EMPTY_SQL = "VALIDATION_EMPTY_SQL"
VALIDATION_SQL_TOO_LONG = "VALIDATION_SQL_TOO_LONG"
VALIDATION_INVALID_PROMPT = "VALIDATION_INVALID_PROMPT"

# NOT_FOUND エラー（404）
NOT_FOUND_PROBLEM = "NOT_FOUND_PROBLEM"
NOT_FOUND_TABLES = "NOT_FOUND_TABLES"

# DATABASE エラー（500）
DATABASE_CONNECTION = "DATABASE_CONNECTION"
DATABASE_EXECUTION = "DATABASE_EXECUTION"
DATABASE_TIMEOUT = "DATABASE_TIMEOUT"
DATABASE_SYNTAX = "DATABASE_SYNTAX"

# LLM エラー（500/503）
LLM_CONNECTION = "LLM_CONNECTION"
LLM_TIMEOUT = "LLM_TIMEOUT"
LLM_INVALID_RESPONSE = "LLM_INVALID_RESPONSE"
LLM_GENERATION_FAILED = "LLM_GENERATION_FAILED"

# INTERNAL エラー（500）
INTERNAL_ERROR = "INTERNAL_ERROR"